from enum import Enum

class IfcWindowTypePartitioningEnum(Enum):
  DOUBLE_PANEL_HORIZONTAL = 1
  DOUBLE_PANEL_VERTICAL = 2
  SINGLE_PANEL = 3
  TRIPLE_PANEL_BOTTOM = 4
  TRIPLE_PANEL_HORIZONTAL = 5
  TRIPLE_PANEL_LEFT = 6
  TRIPLE_PANEL_RIGHT = 7
  TRIPLE_PANEL_TOP = 8
  TRIPLE_PANEL_VERTICAL = 9 
  USERDEFINED = 10
  NOTDEFINED = 11
 